# One-off EC2 Spot instance for ODM reconstruction runs.
# Local state (like infra/storage/) — no Terragrunt, no state bucket needed.
#
# Quick start:
#   cd infra/ec2
#   terraform init
#   terraform apply
#   terraform output instructions
#
# Tear down when done:
#   terraform destroy

terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
    tls = { source = "hashicorp/tls", version = "~> 4.0" }
  }
  backend "local" {}
}

provider "aws" {
  region  = var.region
  profile = "personal"
}

# ── Variables ──────────────────────────────────────────────────────────────────

variable "region" {
  description = "AWS region"
  default     = "us-west-2"
}

variable "bucket_name" {
  description = "S3 bucket containing flight data"
  default     = "stratus-jrstear"
}

variable "instance_type" {
  description = "EC2 instance type. m5.4xlarge = 16 vCPU / 64 GB — good balance of RAM and cores for ODM."
  default     = "m5.4xlarge"
  # Account default on-demand vCPU limit = 32; Spot quota = 0 (request increase via Service Quotas if desired).
  # Alternatives within 32 vCPU limit: c5.4xlarge (16/32GB), m5.8xlarge (32/128GB)
}

variable "ssh_cidr" {
  description = "CIDR allowed to SSH in. 0.0.0.0/0 is fine for a temporary run instance."
  default     = "0.0.0.0/0"
}

# ── SSH Key (generated by Terraform) ──────────────────────────────────────────

resource "tls_private_key" "odm" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "odm" {
  key_name   = "geo-odm-ec2"
  public_key = tls_private_key.odm.public_key_openssh
  tags       = { Project = "geo" }
}

# ── IAM instance profile with S3 access ───────────────────────────────────────

data "aws_iam_policy_document" "ec2_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "odm" {
  name               = "geo-odm-ec2-role"
  assume_role_policy = data.aws_iam_policy_document.ec2_assume.json
  tags               = { Project = "geo" }
}

data "aws_iam_policy_document" "s3_access" {
  statement {
    effect  = "Allow"
    actions = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
    resources = [
      "arn:aws:s3:::${var.bucket_name}",
      "arn:aws:s3:::${var.bucket_name}/*",
    ]
  }
}

resource "aws_iam_role_policy" "odm_s3" {
  name   = "geo-odm-s3"
  role   = aws_iam_role.odm.name
  policy = data.aws_iam_policy_document.s3_access.json
}

resource "aws_iam_instance_profile" "odm" {
  name = "geo-odm-ec2-profile"
  role = aws_iam_role.odm.name
}

# ── Security group ─────────────────────────────────────────────────────────────

resource "aws_security_group" "odm" {
  name        = "geo-odm-ec2-sg"
  description = "SSH ingress + all egress for ODM EC2 run"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Project = "geo" }
}

# ── AMI — Amazon Linux 2023 (x86_64, for c5 family) ──────────────────────────

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
  filter {
    name   = "state"
    values = ["available"]
  }
}

# ── EC2 Spot instance ──────────────────────────────────────────────────────────

resource "aws_instance" "odm" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  iam_instance_profile   = aws_iam_instance_profile.odm.name
  key_name               = aws_key_pair.odm.key_name
  vpc_security_group_ids = [aws_security_group.odm.id]

  # On-demand (Spot quota = 0 on this account; request increase via Service Quotas if desired)

  root_block_device {
    volume_size = 300   # GB: ~14 GB images + 5-8× ODM working space + outputs (150 GB was too tight at high quality)
    volume_type = "gp3"
    throughput  = 250   # MB/s
    iops        = 3000
  }

  user_data = base64encode(<<-EOF
    #!/bin/bash
    set -euo pipefail
    dnf update -y
    dnf install -y docker screen htop
    systemctl enable --now docker
    usermod -aG docker ec2-user
    # Pull ODM in background — large image (~4 GB), takes a few minutes
    docker pull opendronemap/odm:latest &
    echo "user-data complete" | tee /var/log/user-data-done
  EOF
  )

  tags = {
    Project = "geo"
    Purpose = "odm-run"
    Name    = "geo-odm-ec2"
  }
}

# ── Outputs ────────────────────────────────────────────────────────────────────

output "public_ip" {
  value = aws_instance.odm.public_ip
}

output "instance_id" {
  value = aws_instance.odm.id
}

output "private_key_pem" {
  value       = tls_private_key.odm.private_key_pem
  sensitive   = true
  description = "Save with: terraform output -raw private_key_pem > ~/.ssh/geo-odm-ec2.pem && chmod 600 ~/.ssh/geo-odm-ec2.pem"
}

output "instructions" {
  value = <<-EOT

    ── 1. Save SSH key (run once) ────────────────────────────────────────────────
    cd infra/ec2
    terraform output -raw private_key_pem > ~/.ssh/geo-odm-ec2.pem
    chmod 600 ~/.ssh/geo-odm-ec2.pem

    ── 2. SSH in ─────────────────────────────────────────────────────────────────
    ssh -i ~/.ssh/geo-odm-ec2.pem ec2-user@${aws_instance.odm.public_ip}

    ── 3. On the instance (wait ~3 min for user-data + Docker pull) ──────────────
    # Check Docker pull is done:
    docker images    # should show opendronemap/odm

    # Download data from S3 (instance IAM profile handles auth, no keys needed):
    mkdir -p /data/project/images
    aws s3 sync s3://${var.bucket_name}/bsn/aztec/raw/ /data/project/images/ \
      --exclude "*.MRK" --exclude "*.nav" --exclude "*.obs" --exclude "*.bin" \
      --region ${var.region}
    aws s3 cp s3://${var.bucket_name}/bsn/aztec/gcp_confirmed.txt \
      /data/project/gcp_list.txt --region ${var.region}

    ── 4. Run ODM in screen (3–6 hrs at high quality) ────────────────────────────
    screen -S odm
    docker run --rm \
      -v /data/project:/datasets/project \
      opendronemap/odm:latest \
      --project-path /datasets project \
      --pc-quality high \
      --dsm --dtm \
      --orthophoto-resolution 2
    # Ctrl+A, D  →  detach screen
    # screen -r odm  →  reattach

    ── 5. Upload outputs ─────────────────────────────────────────────────────────
    aws s3 sync /data/project/odm_orthophoto/ \
      s3://${var.bucket_name}/bsn/aztec/outputs/odm_orthophoto/ --region ${var.region}
    aws s3 sync /data/project/odm_dem/ \
      s3://${var.bucket_name}/bsn/aztec/outputs/odm_dem/ --region ${var.region}
    aws s3 sync /data/project/odm_report/ \
      s3://${var.bucket_name}/bsn/aztec/outputs/odm_report/ --region ${var.region}
    # Full project dir (includes reconstruction.json, point cloud, etc.):
    aws s3 sync /data/project/ \
      s3://${var.bucket_name}/bsn/aztec/outputs/full/ \
      --exclude "images/*" --region ${var.region}

    ── 6. Tear down (from local machine) ────────────────────────────────────────
    cd infra/ec2 && terraform destroy

  EOT
}
